disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- trailing_whitespace
- type_name
- todo
- inert_defer
- reduce_boolean
- syntactic_sugar

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

function_body_length:
- 39 # warning
- 40 #error

file_length:
- 799 # warning
- 800 # error

type_body_length:
- 99 # warning
- 100 # error

line_length:
- 199 # warning
- 200 # error

cyclomatic_complexity:
- 6 # warning
- 7 # error

excluded:
- Carthage
